#!/usr/bin/env python3

import argparse


def main():
    parser = argparse.ArgumentParser(description='Process to discount on bus')
    parser.add_argument(type=int, dest='price',
                        help='Enter a cost of one trip')
    parser.add_argument(type=int, dest='balancecard',
                        help='Enter the amount you wish to card')
    args = parser.parse_args()
    price = args.price
    balancecard = args.balancecard
    return price, balancecard


def out():
    balancecard, price, totaltrips = discount_on_bus()
    print("After 11 trips your balance has decreased by: "
      "{} with the new cost: "
      "{} you have enough on: {} travels."
      .format(balancecard, price, totaltrips))


def discount_on_bus():
    price, balancecard = main()
    totaltrips = balancecard // price
    while totaltrips >= 12 and price >= 12 and balancecard > 1:
        price -= 2
        balancecard -= price * 12
        totaltrips = balancecard // price
        result = []
        result.append(balancecard)
        result.append(price)
        result.append(totaltrips)
        return result
        if price <= 12 or balancecard <= 0:
            break


if __name__ == '__main__':
    out()
