#!/usr/bin/env python3
def discount_on_bus():
    import argparse
    parser = argparse.ArgumentParser(description='Process to discount on bus')
    parser.add_argument(type=int, dest='price', help='Enter a cost'
                        ' of one trip')
    parser.add_argument(type=int, dest='balancecard', help='Enter the amount'
                        ' you wish to card')
    args = parser.parse_args()
    totaltrips = args.balancecard // args.price
    while totaltrips >= 11 and args.price >= 12 and args.balancecard > 1:
        args.price -= 2
        args.balancecard -= args.price * 11
        totaltrips = args.balancecard // args.price
        if args.price <= 12 or args.balancecard < 0:
            break
        print(
              "After 11 trips your balance has decreased by:"
              "{} with the new cost:"
              " {} you have enough on: {} travels."
              .format(args.balancecard, args.price, totaltrips)
             )
if __name__ == '__main__':
    discount_on_bus()
